apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yml --profile app-notificaciones
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: db-notificaciones
  name: db-notificaciones
spec:
  type: NodePort
  ports:
    - name: "5435"
      port: 5435
      targetPort: 5432
  selector:
    io.kompose.service: db-notificaciones
