apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yml --profile app-notificaciones
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: db-notificaciones
  name: db-notificaciones
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-notificaciones
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../docker-compose.yml --profile app-notificaciones
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: db-notificaciones
    spec:
      containers:
        - env:
            - name: PGUSER
              value: postgres
            - name: POSTGRES_DB
              value: notificaciones
            - name: POSTGRES_PASSWORD
              value: "123456"
            - name: POSTGRES_USER
              value: postgres
          image: postgres:15-alpine
          livenessProbe:
            exec:
              command:
                - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
            failureThreshold: 5
            periodSeconds: 40
            timeoutSeconds: 20
          name: db-notificaciones
          ports:
            - containerPort: 5435
              protocol: TCP
          resources:
            requests:
              cpu: "250m"    # 0.25 vCPU (mínimo en Autopilot)
              memory: "256Mi" # 256 MB de RAM
            limits:
              cpu: "500m"    # 0.5 vCPU
              memory: "512Mi" # 512 MB de RAM
      restartPolicy: Always
