apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yml --profile app-notificaciones
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: ms-notificaciones
  name: ms-notificaciones
spec:
  type: ClusterIP
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    io.kompose.service: ms-notificaciones
