apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yml --profile app-clientes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: ms-gestionclientes
  name: ms-gestionclientes
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ms-gestionclientes
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../docker-compose.yml --profile app-clientes
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: ms-gestionclientes
    spec:
      containers:
        - args:
            - flask
            - --debug
            - run
            - --host=0.0.0.0
            - --port=5000
          env:
            - name: BROKER_HOST
              value: 34.72.58.111
            - name: DB_HOST_URL
              value: db-clientes
            - name: DB_NAME
              value: gestionclientes
            - name: DB_PASSWORD
              value: "123456"
            - name: DB_PORT
              value: "5433"
            - name: DB_USER
              value: postgres
            - name: FLASK_APP
              value: src/gestionclientes/api
            - name: FLASK_ENV
              value: development
          image: us-central1-docker.pkg.dev/monomaster-saludtech/saludtech/ms_gestionclientes:latest
          name: ms-gestionclientes
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            requests:
              cpu: "250m"    # 0.25 vCPU (mínimo en Autopilot)
              memory: "256Mi" # 256 MB de RAM
            limits:
              cpu: "500m"    # 0.5 vCPU
              memory: "512Mi" # 512 MB de RAM
          readinessProbe:
            httpGet:
              path: /health
              port: 5000                
            initialDelaySeconds: 20
            periodSeconds: 60
      # hostname: clientes
      restartPolicy: Always
