apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yml --profile bff
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: bff
  name: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bff
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../docker-compose.yml --profile bff
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: bff
    spec:
      containers:
        - env:
            - name: BROKER_HOST
              value: 34.72.58.111
            - name: SALUDTECH_ADDRESS
              value: ms-gestionclientes
          image: us-central1-docker.pkg.dev/monomaster-saludtech/saludtech/bff:latest
          name: bff
          ports:
            - containerPort: 8003
              protocol: TCP
          resources:
            requests:
              cpu: "250m"    # 0.25 vCPU (mínimo en Autopilot)
              memory: "256Mi" # 256 MB de RAM
            limits:
              cpu: "500m"    # 0.5 vCPU
              memory: "512Mi" # 512 MB de RAM
          readinessProbe:
            httpGet:
              path: /health
              port: 8003                
            initialDelaySeconds: 20
            periodSeconds: 60
      hostname: bff
      restartPolicy: Always
