apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yml --profile app-pagos
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: ms-integracionpagos
  name: ms-integracionpagos
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ms-integracionpagos
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../docker-compose.yml --profile app-pagos
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: ms-integracionpagos
    spec:
      containers:
        - env:
            - name: BROKER_HOST
              value: 34.72.58.111
            - name: DB_HOST_URL
              value: db-pagos
            - name: DB_NAME
              value: integracionpagos
            - name: DB_PASSWORD
              value: "123456"
            - name: DB_PORT
              value: "5434"
            - name: DB_USER
              value: postgres
            - name: FLASK_APP
              value: src/integracionpagos
            - name: FLASK_ENV
              value: development
            - name: PULSAR_ADDRESS
              value: 34.72.58.111
          image: us-central1-docker.pkg.dev/monomaster-saludtech/saludtech/ms_integracion_pagos:latest
          name: ms-integracionpagos
          resources:
            requests:
              cpu: "250m"    # 0.25 vCPU (mínimo en Autopilot)
              memory: "256Mi" # 256 MB de RAM
            limits:
              cpu: "500m"    # 0.5 vCPU
              memory: "512Mi" # 512 MB de RAM
      hostname: pagos
      restartPolicy: Always
